// src/constants/stateTax.ts
export const STATETAX_DATA = [
    { name: "Alabama", url: "https://revenue.alabama.gov/" },
    { name: "Alaska", url: "https://dor.alaska.gov/" },
    { name: "Arizona", url: "https://azdor.gov/" },
    { name: "Arkansas", url: "https://www.dfa.arkansas.gov/" },
    { name: "California", url: "https://www.ftb.ca.gov/" },
    { name: "Colorado", url: "https://tax.colorado.gov/" },
    { name: "Connecticut", url: "https://portal.ct.gov/drs" },
    { name: "Delaware", url: "https://revenue.delaware.gov/" },
    { name: "District of Columbia", url: "https://otr.cfo.dc.gov/" },
    { name: "Georgia", url: "https://dor.georgia.gov/taxes" },
    { name: "Hawaii", url: "https://tax.hawaii.gov/" },
    { name: "Idaho", url: "https://tax.idaho.gov/" },
    { name: "Illinois", url: "https://www2.illinois.gov/rev/Pages/default.aspx" },
    { name: "Indiana", url: "https://www.in.gov/dor/" },
    { name: "Iowa", url: "https://tax.iowa.gov/" },
    { name: "Kansas", url: "https://www.ksrevenue.org/" },
    { name: "Kentucky", url: "https://revenue.ky.gov/" },
    { name: "Louisiana", url: "https://revenue.louisiana.gov/" },
    { name: "Maine", url: "https://www.maine.gov/revenue/" },
    { name: "Maryland", url: "https://www.marylandtaxes.gov/" },
    { name: "Massachusetts", url: "https://www.mass.gov/orgs/massachusetts-department-of-revenue" },
    { name: "Michigan", url: "https://www.michigan.gov/taxes" },
    { name: "Minnesota", url: "https://www.revenue.state.mn.us/" },
    { name: "Mississippi", url: "https://www.dor.ms.gov/" },
    { name: "Missouri", url: "https://dor.mo.gov/" },
    { name: "Montana", url: "https://mtrevenue.gov/" },
    { name: "Nebraska", url: "https://revenue.nebraska.gov/" },
    { name: "Nevada", url: "https://tax.nv.gov/" },
    { name: "New Hampshire", url: "https://www.revenue.nh.gov/" },
    { name: "New Jersey", url: "https://www.state.nj.us/treasury/taxation/" },
    { name: "New Mexico", url: "https://www.tax.newmexico.gov/" },
    { name: "New York", url: "https://www.tax.ny.gov/" },
    { name: "North Carolina", url: "https://www.ncdor.gov/" },
    { name: "North Dakota", url: "https://www.tax.nd.gov/" },
    { name: "Ohio", url: "https://www.tax.ohio.gov/" },
    { name: "Oklahoma", url: "https://oklahoma.gov/tax/individuals.html" },
    { name: "Oregon", url: "https://www.oregon.gov/dor/" },
    { name: "Pennsylvania", url: "https://www.revenue.pa.gov/" },
    { name: "Rhode Island", url: "https://tax.ri.gov/" },
    { name: "South Carolina", url: "https://dor.sc.gov/" },
    { name: "South Dakota", url: "https://dor.sd.gov/" },
    { name: "Tennessee", url: "https://www.tn.gov/revenue/" },
    { name: "Texas", url: "https://comptroller.texas.gov/" },
    { name: "Utah", url: "http://incometax.utah.gov/" },
    { name: "Vermont", url: "https://tax.vermont.gov/" },
    { name: "Virginia", url: "https://www.tax.virginia.gov/" },
    { name: "Washington", url: "https://dor.wa.gov/" },
    { name: "West Virginia", url: "http://tax.wv.gov/" },
    { name: "Wisconsin", url: "https://www.revenue.wi.gov/" },
    { name: "Wyoming", url: "https://revenue.wyo.gov/" }
];
